# Generated by Django 3.1.3 on 2020-11-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine21',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('site', models.CharField(max_length=200)),
                ('grapes', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('howto', models.CharField(max_length=200)),
                ('alchol', models.CharField(max_length=50)),
                ('dang', models.IntegerField(default=0)),
                ('san', models.IntegerField(default=0)),
                ('body', models.IntegerField(default=0)),
                ('tannin', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('goodsno', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Winenara',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('types', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('alchol', models.CharField(max_length=50)),
                ('vintage', models.CharField(max_length=50)),
                ('grapes', models.CharField(max_length=200)),
                ('san', models.IntegerField(default=0)),
                ('dang', models.IntegerField(default=0)),
                ('body', models.IntegerField(default=0)),
                ('nation', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('goodsno', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Winenara_temp',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('types', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('alchol', models.CharField(max_length=50)),
                ('vintage', models.CharField(max_length=50)),
                ('grapes', models.CharField(max_length=200)),
                ('san', models.IntegerField(default=0)),
                ('dang', models.IntegerField(default=0)),
                ('body', models.IntegerField(default=0)),
                ('nation', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('goodsno', models.IntegerField(default=0)),
            ],
        ),
    ]
