# Generated by Django 3.1.3 on 2020-11-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wine21_temp',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('site', models.CharField(max_length=200)),
                ('grapes', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
                ('howto', models.CharField(max_length=200)),
                ('alchol', models.CharField(max_length=50)),
                ('dang', models.IntegerField(default=0)),
                ('san', models.IntegerField(default=0)),
                ('body', models.IntegerField(default=0)),
                ('tannin', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('goodsno', models.IntegerField(default=0)),
            ],
        ),
    ]
